from setuptools import setup, find_packages

setup(
    name="xenoworlds",
    version="1.0.0",
    url="https://github.com/rbalestr-lab/xenoworlds",
    author="Randall Balestriero",
    author_email="randallbalestriero@gmail.com",
    description="Description of my package",
    packages=find_packages(),
    install_requires=[
        "torch",
        "torchvision",
        "torchaudio",
        "hydra-core",
        "hydra-joblib-launcher",
        "hydra-submitit-launcher",
        "hydra-optuna-sweeper==1.3.0.dev0",
        "submitit",
        "tqdm",
        "transformers",
        "wandb",
        "matplotlib",
        "tabulate",
        "datasets",
        "minigrid",
        "rich",
        "mujoco",
        "gymnasium>=1.2.0",
        "swig",
        "gymnasium[box2d]",
        "d4rl",
        "gymnasium[other]",
        "gymnasium[mujoco]",
        "gymnasium-robotics",
        "imageio[ffmpeg]",
        "tensorboard",
        "loguru",
        "pytest",
        "scikit-learn",
        "av",
        "prettytable",
        "nevergrad",
    ],
)
