# @package _global_
# Local launcher configuration (no SLURM)

defaults:
  - override /hydra/launcher: basic

dataset_name: pusht_expert_video_train

n_gpus: 1
cpus_per_task: 8
cache_dir: null # Use stable-worldmodel default cache
wandb:
  use_wandb: false
  entity: stable-wm
  project: stable-wm
