name: build_sphinx_docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build_docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[docs]"

      - name: Remove all .rst files except index.rst
        run: |
          find docs/source -type f -name "*.rst" ! -name "index.rst" -exec rm -f {} \;

      - name: Generate .rst files from package
        run: |
          sphinx-apidoc -o docs/source stable_worldmodel

      - name: Build Sphinx HTML documentation
        run: |
          cd docs
          sphinx-build -b html source build/html

      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: sphinx-html
          path: docs/build/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
